modLoader = "javafml"
loaderVersion = "[${versions.forge_dependency},)"
license = "MIT"

[[mods]]
modId = "hexdebug"
version = "${version}"
displayName = "HexDebug"
logoFile = "icon.png"
authors = "object-Object"
description = '''
The HexDebug addon for Hex Casting
'''

[[dependencies.hexdebug]]
modId = "forge"
mandatory = true
versionRange = "[${versions.forge_dependency},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexdebug]]
modId = "minecraft"
mandatory = true
versionRange = "[${versions.minecraft},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexdebug]]
modId = "architectury"
mandatory = true
versionRange = "[${versions.architectury},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexdebug]]
modId = "hexcasting"
mandatory = true
versionRange = "[${versions.hexcasting},)"
ordering = "NONE"
side = "BOTH"
