name: Run CI/CD pipeline

on:
  push:
    branches: "*"
  pull_request:
  workflow_dispatch:
    inputs:
      publish-mod:
        description: Publish the mod
        type: boolean
        default: false
      publish-docs:
        description: Publish the web book
        type: boolean
        default: false

env:
  PYPI_PACKAGE: hexdoc-hexdebug

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      is-main-branch: |-
        ${{
          github.event_name != 'pull_request' && contains(
            fromJson('["main"]'),
            (github.head_ref || github.ref_name)
          )
        }}
      branch-name:  ${{ github.head_ref || github.ref_name }}
      publish-mod:  ${{ github.event_name == 'workflow_dispatch' && inputs.publish-mod == 'true' }}
      publish-docs: ${{ github.event_name == 'workflow_dispatch' && inputs.publish-docs == 'true' }}
    steps:
      - run: 'echo "event_name: ${{ github.event_name }}"'
      - run: 'echo "inputs: ${{ toJson(inputs) }}"'

  build-mod:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3

      - name: Build mod
        run: ./gradlew build

      # literally no idea why the mkdir is needed, but the workflow fails without it :/
      - name: Check if datagen needs to be run
        timeout-minutes: 3
        run: |
          mkdir -p /home/runner/.gradle/caches/fabric-loom/assets
          ./gradlew runAllDatagen
          git add --intent-to-add .
          git diff --name-only --exit-code -- ":!:*/src/generated/resources/.cache/*"

      - name: Prepare prerelease artifact
        run: |
          mkdir dist
          cp {Common,Fabric,Forge}/build/libs/*.jar dist

      - name: Upload prerelease artifact
        uses: actions/upload-artifact@v4
        with:
          name: mod-prerelease
          path: dist/
          if-no-files-found: error

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: mod-build
          path: '*/build'
          if-no-files-found: error

  build-docs:
    needs: setup
    uses: hexdoc-dev/hexdoc/.github/workflows/hexdoc.yml@v1!0.1.dev
    permissions:
      contents: write
      pages: read
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      python-version: 3.11
      deploy-pages: ${{ needs.setup.outputs.publish-docs == 'true' || needs.setup.outputs.is-main-branch == 'true' }}
      release: ${{ needs.setup.outputs.publish-docs == 'true' }}

  publish-mod:
    needs: [setup, build-mod, build-docs]
    if: needs.setup.outputs.publish-mod == 'true'
    runs-on: ubuntu-latest
    # environment:
    #   name: curseforge-modrinth
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: mod-build

      - name: Publish mod
        env:
          DRY_RUN: 1
          CURSEFORGE_TOKEN:
          MODRINTH_TOKEN:
          GITHUB_TOKEN:
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
        run: ./gradlew publishMods

      - name: Upload mod publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: mod-publish
          path: '*/build/publishMods'
          if-no-files-found: error

  publish-docs:
    needs: [setup, build-mod, build-docs]
    if: needs.setup.outputs.publish-docs == 'true'
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/${{ env.PYPI_PACKAGE }}
    permissions:
      id-token: write
    steps:
      # hexdoc workflow uses v3, so we can't use v4 here
      - uses: actions/download-artifact@v3
        with:
          name: hexdoc-build
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
