name: Release

on:
  workflow_dispatch:
    inputs:
      publish-mod:
        description: Publish the mod
        type: boolean
        default: false
      publish-docs:
        description: Publish the web book
        type: boolean
        default: false
      dry-run:
        description: Dry run
        type: boolean
        default: false

env:
  PYPI_PACKAGE: hexdoc-hexdebug

permissions:
  contents: read

jobs:
  build-docs:
    uses: hexdoc-dev/hexdoc/.github/workflows/hexdoc.yml@v1!0.1.dev
    permissions:
      contents: write
      pages: read
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      python-version: 3.11
      deploy-pages: ${{ inputs.publish-docs && !inputs.dry-run }}
      release: true

  publish-mod:
    needs: build-docs
    if: inputs.publish-mod
    runs-on: ubuntu-latest
    environment:
      name: curseforge-modrinth
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3

      - name: Build mod
        run: ./gradlew build

      - name: Publish mod
        env:
          DRY_RUN: ${{ inputs.dry-run && 'true' || '' }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publishMods

      - name: Upload dry run artifact
        if: inputs.dry-run
        uses: actions/upload-artifact@v4
        with:
          name: mod-publish
          path: '*/build/publishMods'
          if-no-files-found: error

  publish-docs:
    needs: build-docs
    if: inputs.publish-docs && !inputs.dry-run
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/${{ env.PYPI_PACKAGE }}
    permissions:
      id-token: write
    steps:
      # hexdoc workflow uses v3, so we can't use v4 here
      - uses: actions/download-artifact@v3
        with:
          name: hexdoc-build
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
